sudo: required
language: python
services:
  - docker
install:
  - echo "Nothing to install"
jobs:
  include:
    - stage: deploy
      if: branch = master OR branch = develop
      script:
        - travis_wait 30 docker build --build-arg GITHUB_PAT=$GITHUB_PAT -t openstudio-rnotebook:latest .
      after_success:
        - ./deploy_docker.sh